"""create twitter_posts table

Revision ID: 360e648fd3ab
Revises: 
Create Date: 2024-12-20 13:39:27.822310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '360e648fd3ab'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('twitter_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('MATCH_CREATED', 'MATCH_JOINED', 'MATCH_COMPLETED', 'TOURNAMENT_CREATED', 'DAILY_STATS', name='posttype'), nullable=False),
    sa.Column('reference_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILED', 'PENDING', name='poststatus'), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('tweet_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('twitter_posts')
    # ### end Alembic commands ###
